apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    type: web
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: python-app
          image: xerosoft/python-app
          ports:
            - containerPort: 80
          env:
            - name: GET_HOSTS_FROM
              value: env
