apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    tier: backend
    type: db
    role: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        type: db
        role: master
        name: redis-master
    spec:
      containers:
        - name: redis-master
          image: redis
          ports:
            - containerPort: 6379
